"""
Vector store — ChromaDB running fully locally (no server, embedded mode).

Embeddings are generated by nomic-embed-text via the local Ollama instance,
so no text ever leaves the machine.
"""
from __future__ import annotations
import hashlib
import uuid
import chromadb
from chromadb.config import Settings as ChromaSettings
import ollama

from config.settings import settings

# Fallback dimension when Ollama is unavailable. Matches nomic-embed-text so stub
# and real vectors can coexist in one collection (an 8-dim stub would make ChromaDB
# raise on dimension mismatch). ponytail: 768 hard-coded; if you swap embedding
# models to a different dim AND run offline, set this to match.
_STUB_DIM = 768


_client: chromadb.ClientAPI | None = None
_collection: chromadb.Collection | None = None


def _get_collection() -> chromadb.Collection:
    global _client, _collection
    if _collection is None:
        settings.chroma_dir.mkdir(parents=True, exist_ok=True)
        _client = chromadb.PersistentClient(
            path=str(settings.chroma_dir),
            settings=ChromaSettings(anonymized_telemetry=False),
        )
        _collection = _client.get_or_create_collection(
            name="memories",
            metadata={"hnsw:space": "cosine"},
        )
    return _collection


def _hash_embed(text: str) -> list[float]:
    # Deterministic, dimension-stable fallback when Ollama is down. Not semantically
    # meaningful — search degrades to FTS5 + graph signals — but keeps the app running
    # offline instead of 500-ing every write/search (the trust gate embeds on every write).
    out: list[float] = []
    i = 0
    while len(out) < _STUB_DIM:
        out.extend(b / 255.0 for b in hashlib.sha256(f"{i}:{text}".encode()).digest())
        i += 1
    return out[:_STUB_DIM]


def embed(text: str) -> list[float]:
    """Generate embedding via local Ollama — zero external API calls. Falls back to a
    deterministic hash stub if Ollama is unavailable, so the app works offline."""
    try:
        return ollama.embeddings(model=settings.embedding_model, prompt=text)["embedding"]
    except Exception:
        return _hash_embed(text)


def upsert(memory_id: str, content: str, metadata: dict) -> None:
    col = _get_collection()
    embedding = embed(content)
    col.upsert(
        ids=[memory_id],
        embeddings=[embedding],
        documents=[content],
        metadatas=[{k: str(v) for k, v in metadata.items()}],
    )


def search(query: str, n_results: int = 10, where: dict | None = None) -> list[dict]:
    """Return top-N semantically similar memories."""
    col = _get_collection()
    q_embed = embed(query)
    kwargs: dict = {"query_embeddings": [q_embed], "n_results": min(n_results, col.count() or 1)}
    if where:
        kwargs["where"] = where
    results = col.query(**kwargs)
    out = []
    for i, doc_id in enumerate(results["ids"][0]):
        out.append({
            "id": doc_id,
            "content": results["documents"][0][i],
            "distance": results["distances"][0][i],
            "metadata": results["metadatas"][0][i],
        })
    return out


def similarity(content_a: str, content_b: str) -> float:
    """Cosine similarity between two strings (1 = identical, 0 = orthogonal)."""
    ea, eb = embed(content_a), embed(content_b)
    dot = sum(a * b for a, b in zip(ea, eb))
    na = sum(a ** 2 for a in ea) ** 0.5
    nb = sum(b ** 2 for b in eb) ** 0.5
    return dot / (na * nb) if na and nb else 0.0


def delete(memory_id: str) -> None:
    _get_collection().delete(ids=[memory_id])

def count() -> int:
    try:
        return _get_collection().count()
    except Exception:
        return 0

